<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="chat-page" id="direct-chat" data-poll-url="<?= site_url('messages/'.$conversation['id'].'/poll') ?>" data-history-url="<?= site_url('messages/'.$conversation['id'].'/history') ?>" data-send-url="<?= site_url('messages/'.$conversation['id'].'/send') ?>" data-delete-url="<?= site_url('messages/'.$conversation['id'].'/delete/__ID__') ?>" data-current-user="<?= $userId ?>" data-csrf-name="<?= csrf_token() ?>" data-csrf-hash="<?= csrf_hash() ?>">
    <header class="chat-head"><div><a class="chat-back" href="<?= site_url('messages') ?>">← Mesajlar</a><h1><a href="<?= site_url('users/'.$otherUser['id']) ?>"><?= esc($otherUser['username']) ?></a></h1><small><?= (int)$otherUser['is_active']===1?'Aktif hesap':'Devre dışı hesap' ?></small></div><div class="chat-user-actions"><?php if($blockedByMe): ?><form method="post" action="<?= site_url('messages/unblock/'.$otherUser['id']) ?>"><?= csrf_field() ?><button class="button secondary" type="submit">Engeli kaldır</button></form><?php else: ?><form method="post" action="<?= site_url('messages/block/'.$otherUser['id']) ?>" onsubmit="return confirm('Bu kullanıcı engellensin mi? Artık birbirinize mesaj gönderemeyeceksiniz.')"><?= csrf_field() ?><button class="button danger" type="submit">Engelle</button></form><?php endif; ?></div></header>

    <div class="chat-list" id="chat-list" aria-live="polite">
        <?php if ($hasOlder): ?><button class="load-older" id="load-older" type="button">Daha eski mesajları yükle</button><?php endif; ?>
        <?php if ($messages === []): ?><p class="chat-empty" id="chat-empty">Henüz mesaj yok. İlk mesajı siz gönderin.</p><?php endif; ?>
        <?php foreach($messages as $message): $mine=(int)$message['sender_id']===$userId; ?>
            <article class="chat-message <?= $mine?'mine':'theirs' ?>" data-message-id="<?= $message['id'] ?>" data-mine="<?= $mine?'1':'0' ?>"><p><?= esc($message['body']) ?></p><footer><time><?= date('d.m.Y · H:i',strtotime($message['created_at'])) ?></time><?php if($mine): ?><span class="read-state"><?= $message['read_at']?'Okundu':'Gönderildi' ?></span><?php endif; ?><form method="post" action="<?= site_url('messages/'.$conversation['id'].'/delete/'.$message['id']) ?>" onsubmit="return confirm('Bu mesaj sizin görünümünüzden silinsin mi?')"><?= csrf_field() ?><button type="submit">Sil</button></form></footer></article>
        <?php endforeach; ?>
    </div>

    <?php if($blockedByMe): ?><div class="chat-blocked">Bu kullanıcıyı engellediniz. Mesaj göndermek için engeli kaldırın.</div><?php elseif($blockedByOther): ?><div class="chat-blocked">Bu konuşmada şu anda mesaj gönderemezsiniz.</div><?php elseif((int)$otherUser['is_active']!==1): ?><div class="chat-blocked">Bu hesap devre dışı olduğu için mesaj gönderilemez.</div><?php else: ?>
        <form class="chat-form" id="chat-form"><label class="sr-only" for="chat-body">Mesajınız</label><textarea id="chat-body" name="body" maxlength="2000" rows="2" placeholder="Bir mesaj yazın…" required></textarea><div><small><span id="chat-count">0</span>/2000</small><button class="button" id="chat-send" type="submit">Gönder</button></div><p id="chat-error" role="alert"></p></form>
    <?php endif; ?>
</section>
<style>.chat-page{max-width:850px;margin:auto}.chat-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-bottom:15px;border-bottom:1px solid #e5e7eb}.chat-head h1{margin:5px 0 2px}.chat-head h1 a{color:inherit;text-decoration:none}.chat-head small,.chat-back{color:#6b7280}.chat-user-actions form{margin:0}.chat-list{display:flex;min-height:360px;max-height:62vh;overflow-y:auto;flex-direction:column;gap:10px;padding:20px 5px}.chat-empty{margin:auto;color:#6b7280}.chat-message{max-width:min(76%,620px);padding:11px 13px;border-radius:14px;background:#f3f4f6}.chat-message.mine{align-self:flex-end;border-bottom-right-radius:4px;background:#dbeafe}.chat-message.theirs{align-self:flex-start;border-bottom-left-radius:4px}.chat-message p{margin:0;line-height:1.5;white-space:pre-wrap;overflow-wrap:anywhere}.chat-message footer{display:flex;align-items:center;justify-content:flex-end;gap:8px;margin-top:6px;color:#64748b;font-size:10px}.chat-message footer form{margin:0}.chat-message footer button{padding:0;border:0;background:none;color:#dc2626;font:inherit;cursor:pointer}.read-state{font-weight:700}.chat-form{padding-top:15px;border-top:1px solid #e5e7eb}.chat-form textarea{min-height:74px;max-height:180px}.chat-form>div{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:7px}.chat-form small{color:#6b7280}.chat-form p{min-height:18px;margin:5px 0 0;color:#dc2626}.chat-blocked{padding:14px;border-radius:10px;background:#fef3c7;color:#92400e;text-align:center}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}html[data-theme="dark"] .chat-head,html[data-theme="dark"] .chat-form{border-color:#475569}html[data-theme="dark"] .chat-message{background:#334155}html[data-theme="dark"] .chat-message.mine{background:#1e3a8a}@media(max-width:600px){.chat-head{align-items:flex-start;flex-direction:column}.chat-message{max-width:88%}.chat-list{max-height:58vh}}</style>
<style>.load-older{align-self:center;padding:7px 11px;border:0;border-radius:8px;background:#e5e7eb;color:#374151;cursor:pointer}</style>
<script src="<?= base_url('js/direct-messages.js') ?>"></script>
<?= $this->endSection() ?>
