<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<style>
    .admin-page-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:20px}.admin-page-head h1{margin:0}.log-table-wrap{overflow-x:auto}.log-table{width:100%;border-collapse:collapse}.log-table th,.log-table td{padding:11px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.log-table td{font-size:13px}.log-action{display:inline-block;padding:4px 7px;border-radius:999px;background:#e0e7ff;color:#3730a3;font-size:11px;font-weight:700}.log-status{color:#166534;font-weight:700}.log-status.failed{color:#dc2626}.log-path{max-width:230px;overflow:hidden;color:#6b7280;text-overflow:ellipsis;white-space:nowrap}.pagination{display:flex;flex-wrap:wrap;gap:6px;padding:20px 0 0;list-style:none}.pagination a{display:block;padding:7px 10px;border-radius:7px;background:#e5e7eb;color:#111827;text-decoration:none}@media(max-width:650px){.admin-page-head{align-items:flex-start;flex-direction:column}}
</style>
<header class="admin-page-head"><div><h1>Aktivite Logları</h1><p style="color:#6b7280">Özel içerikler kaydedilmez; yalnızca işlem bilgileri tutulur.</p></div><div><a class="button secondary" href="<?= site_url('admin') ?>">Dashboard</a> <a class="button secondary" href="<?= site_url('admin/users') ?>">Kullanıcılar</a></div></header>
<form class="content-filter" method="get" action="<?= site_url('admin/logs') ?>" style="display:grid;grid-template-columns:1.5fr 1fr 1fr 1fr auto auto;gap:9px;margin-bottom:20px"><input type="search" name="q" value="<?= esc($search) ?>" placeholder="Kullanıcı, işlem veya IP"><select name="action"><option value="">Tüm işlemler</option><?php foreach($actions as $action):?><option value="<?= esc($action,'attr') ?>" <?= $activeAction===$action?'selected':'' ?>><?= esc($action) ?></option><?php endforeach;?></select><select name="status"><option value="">Tüm sonuçlar</option><option value="success" <?= $activeStatus==='success'?'selected':'' ?>>Başarılı</option><option value="failed" <?= $activeStatus==='failed'?'selected':'' ?>>Başarısız</option></select><input type="date" name="date" value="<?= esc($activeDate,'attr') ?>"><button class="button" type="submit">Filtrele</button><a class="button secondary" href="<?= site_url('admin/logs') ?>">Temizle</a></form>
<?php if(empty($logs)):?><p>Bu filtrelere uyan log bulunamadı.</p><?php else:?><div class="log-table-wrap"><table class="log-table"><thead><tr><th>Zaman</th><th>Kullanıcı</th><th>İşlem</th><th>Açıklama</th><th>Yol / IP</th><th>Sonuç</th></tr></thead><tbody><?php foreach($logs as $log):?><tr><td><?= date('d.m.Y H:i:s',strtotime($log['created_at'])) ?></td><td><?= esc($log['username']??'Misafir/Silinmiş') ?></td><td><span class="log-action"><?= esc($log['action']) ?></span></td><td><?= esc($log['description']) ?></td><td><div class="log-path" title="<?= esc($log['path'],'attr') ?>"><?= esc($log['method'].' /'.$log['path']) ?></div><small><?= esc($log['ip_address']) ?></small></td><td><span class="log-status <?= (int)$log['status_code']>=400?'failed':'' ?>"><?= (int)$log['status_code'] ?></span></td></tr><?php endforeach;?></tbody></table></div><?= $pager->links() ?><?php endif;?>
<?= $this->endSection() ?>
