<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<style>
.four-room{max-width:1100px;margin:auto}.four-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.four-code{font-weight:800;letter-spacing:.14em;color:#2563eb}.seat-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:20px 0}.seat{min-height:110px;padding:16px;border:1px solid #dbe3ef;border-radius:14px;background:#fff}.seat.empty{display:grid;place-items:center;border-style:dashed;color:#64748b}.seat-top{display:flex;justify-content:space-between;gap:10px}.seat h3{margin:4px 0}.seat small{color:#64748b}.seat form{margin-top:12px}.bot-panel,.game-placeholder{padding:18px;border:1px solid #dbe3ef;border-radius:14px;background:#f8fafc}.bot-panel form{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.bot-panel select{min-width:180px}.game-placeholder{margin-top:16px;text-align:center}.team-badge{padding:3px 8px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-size:12px;font-weight:700}html[data-theme="dark"] .seat,html[data-theme="dark"] .bot-panel,html[data-theme="dark"] .game-placeholder{background:#1e293b;border-color:#475569}html[data-theme="dark"] .seat small{color:#cbd5e1}@media(max-width:650px){.four-head{flex-direction:column}.seat-grid{grid-template-columns:1fr}.bot-panel form{align-items:stretch}.bot-panel select,.bot-panel button{width:100%}}
</style>
<main class="four-room" id="four-player-game" data-game="<?= esc($room['game']) ?>" data-state-url="<?= site_url('games/room/'.$room['code'].'/four-state') ?>" data-action-url="<?= site_url('games/room/'.$room['code'].'/four-action') ?>" data-csrf-name="<?= csrf_token() ?>" data-csrf-hash="<?= csrf_hash() ?>"><header class="four-head"><div><h1><?= $room['game'] === 'okey101' ? '101 Okey' : 'Monopoly' ?> · Online</h1><p class="four-code">ODA: <?= esc($room['code']) ?></p></div><a class="button secondary" href="<?= site_url('games/multiplayer') ?>">Odalara dön</a></header>
<?php if (session('error')): ?><div class="alert error"><?= esc(session('error')) ?></div><?php endif; ?><?php if (session('success')): ?><div class="alert success"><?= esc(session('success')) ?></div><?php endif; ?>
<section class="seat-grid"><?php $bySeat = array_column($room['players'], null, 'seat'); ?><?php for ($seat=0;$seat<4;$seat++): $player=$bySeat[$seat]??null; ?><?php if ($player): ?><article class="seat"><div class="seat-top"><div><small>Koltuk <?= $seat+1 ?></small><h3><?= esc($player['name']) ?></h3></div><?php if ($player['team']): ?><span class="team-badge">Takım <?= $player['team'] ?></span><?php endif; ?></div><small><?= $player['type']==='bot'?'Bot · '.($player['difficulty']==='hard'?'Zor':'Normal'):'Oyuncu' ?></small><?php if ($room['isOwner']&&$player['type']==='bot'): ?><form method="post" action="<?= site_url('games/room/'.$room['code'].'/bots/'.$seat.'/remove') ?>"><?= csrf_field() ?><button class="button secondary" type="submit">Botu kaldır</button></form><?php endif; ?></article><?php else: ?><article class="seat empty">Oyuncu bekleniyor…</article><?php endif; ?><?php endfor; ?></section>
<?php if ($room['status']==='waiting'&&$room['isOwner']&&count($room['players'])<4): ?><section class="bot-panel"><h2>Boş koltuğa bot ekle</h2><form method="post" action="<?= site_url('games/room/'.$room['code'].'/bots') ?>"><?= csrf_field() ?><label>Bot seviyesi<select name="difficulty"><option value="normal">Normal</option><option value="hard">Zor</option></select></label><button class="button" type="submit">Bot ekle</button></form></section><?php endif; ?>
<?php if ($room['status']==='waiting'): ?><section class="game-placeholder"><strong><?= count($room['players']) ?>/4 oyuncu hazır.</strong><?php if($room['isOwner']&&count($room['players'])===4): ?><form method="post" action="<?= site_url('games/room/'.$room['code'].'/start-four') ?>"><?= csrf_field() ?><button class="button" type="submit">Oyunu başlat</button></form><?php else: ?><p>Dört koltuğun dolması bekleniyor.</p><?php endif; ?></section><?php elseif($room['game']==='okey101'): ?><section id="okey-table" class="game-placeholder"><div id="okey-status"></div><div id="okey-discard"></div><div id="okey-hand" style="display:flex;gap:6px;flex-wrap:wrap;justify-content:center;margin:18px 0"></div><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button class="button" data-okey-action="draw" data-source="deck">Ortadan çek</button><button class="button secondary" data-okey-action="draw" data-source="discard">Yerden çek</button><button class="button" data-okey-action="open">Seçilenleri per aç</button><button class="button secondary" data-okey-action="pairs">Seçilenlerle çift aç</button><button class="button" data-okey-action="discard">Seçileni at</button></div><p id="okey-message" aria-live="polite"></p></section><?php else: ?><section class="game-placeholder"><div id="monopoly-status"></div><div id="monopoly-board" style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px;margin:15px 0"></div><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button class="button" data-monopoly-action="roll">Zar at</button><button class="button" data-monopoly-action="buy">Satın al</button><button class="button secondary" data-monopoly-action="pass">Açık artırmaya çıkar</button><button class="button secondary" data-monopoly-action="end">Turu bitir</button><button class="button secondary" data-monopoly-action="bankrupt">İflas et</button></div><p id="monopoly-message"></p></section><?php endif; ?></main>
<?php if($room['game']==='okey101'&&$room['status']!=='waiting'): ?><script src="<?= base_url('js/okey101.js') ?>"></script><?php endif; ?>
<?php if($room['game']==='monopoly'&&$room['status']!=='waiting'): ?><script src="<?= base_url('js/monopoly.js') ?>"></script><?php endif; ?>
<?= $this->endSection() ?>
