<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?php $games=[['🐍','Yılan Oyunu','Yemi toplayın ve en yüksek çevrimdışı skora ulaşın.','games/snake',false],['▦','Tetris','Satırları temizleyin ve artan hıza ayak uydurun.','games/tetris',false],['💣','Mayın Tarlası','Sayıları kullanarak mayınları bulun ve işaretleyin.','games/minesweeper',false],['9','Sudoku','Satır, sütun ve kutuları üç zorluk seviyesinde tamamlayın.','games/sudoku',false],['9','Sudoku Online','Başka bir oyuncuyla aynı Sudoku tahtasını birlikte çözün.','games/multiplayer?game=sudoku',true],['💣','Mayın Tarlası Online','Aynı mayın tarlasında başka bir oyuncuyla birlikte ilerleyin.','games/multiplayer?game=minesweeper',true],['🐍','Yılan Online','Aynı yem için başka bir oyuncuyla gerçek zamanlı yarışın.','games/multiplayer?game=snake',true],['101','101 Okey Online','Dört oyuncuyla bireysel veya eşli oynayın; bot ya da arkadaş ekleyin.','games/multiplayer?game=okey101',true],['🎩','Monopoly Online','Mülk alın, kira toplayın, açık artırma ve takas yapın.','games/multiplayer?game=monopoly',true]]; ?>
<style>
.games-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;margin-bottom:22px}.games-head h1{margin:0 0 7px}.games-head p{margin:0;color:#6b7280}.join-room{display:flex;gap:8px;align-items:end;padding:12px;border:1px solid #dbeafe;border-radius:13px;background:#eff6ff}.join-room label{font-weight:700}.join-room input{width:150px;height:42px;text-align:center;text-transform:uppercase;letter-spacing:.18em;font-weight:800}.games-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.game-card{display:flex;min-height:245px;flex-direction:column;padding:23px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;position:relative}.game-card.online{border-color:#93c5fd}.online-badge{position:absolute;right:14px;top:14px;padding:4px 8px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-size:11px;font-weight:800}.game-icon{display:grid;width:58px;height:58px;place-items:center;border-radius:15px;background:#e2e8f0;font-size:29px;font-weight:900}.game-card h2{margin:18px 0 8px}.game-card p{flex:1;margin:0 0 20px;color:#6b7280;line-height:1.55}.game-card .button{align-self:flex-start}html[data-theme="dark"] .game-card,html[data-theme="dark"] .join-room{background:#1e293b;border-color:#475569}@media(max-width:900px){.games-grid{grid-template-columns:repeat(2,1fr)}.games-head{align-items:stretch;flex-direction:column}}@media(max-width:650px){.games-grid{grid-template-columns:1fr}.join-room{align-items:stretch;flex-direction:column}.join-room input,.join-room button{width:100%}}
</style>
<header class="games-head"><div><h1>Oyunlar</h1><p>Çevrimdışı oynayın veya arkadaşlarınızla online bir oda açın.</p></div><form class="join-room" method="post" action="<?=site_url('games/multiplayer/join')?>"><?=csrf_field()?><label for="quick-room-code">Oda koduyla katıl</label><input id="quick-room-code" name="code" maxlength="6" minlength="6" autocomplete="off" placeholder="ABC123" required><button class="button" type="submit">Koda git</button></form></header>
<?php if(session('error')):?><div class="alert error"><?=esc(session('error'))?></div><?php endif;?><div class="games-grid"><?php foreach($games as [$icon,$name,$description,$path,$online]):?><article class="game-card<?=$online?' online':''?>"><?php if($online):?><span class="online-badge">ONLINE</span><?php endif;?><span class="game-icon" aria-hidden="true"><?=$icon?></span><h2><?=esc($name)?></h2><p><?=esc($description)?></p><a class="button" href="<?=site_url($path)?>"><?=$online?'Online oda aç':'Oyunu aç'?></a></article><?php endforeach;?></div>
<?= $this->endSection() ?>
